---
title: "Raport deficytow"
author: "Consnensus"
date:
output: html_document
params:
  input_wart: 0
  input_proc: 0
  d1 : "2016-06-01"
  d2 : "2018-05-31"
  points : 0
  CKK : 0
  CKP : 0
---

Data wygenerowania raportu: `r Sys.time()`

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(kableExtra)
source("C:/Users/msiwik/Desktop/FOLDER R/GUI_consensus/global.r", encoding = "UTF-8")
Opis <- "Deficytów"

```


### 1. Dane
```{r, fig.width=8, echo = FALSE}

 dataToPlot <- DaneDoScatter(
      dane = YM_ALL_WSK,
      Platnik = params$CKP,
      CKK = NA,
      input_data_start = params$d1,
      input_data_koniec = params$d2,
      input_proc = params$input_proc,
      input_wart = params$input_wart,
      Wart_COL = "WCSN_DEF",
      WSK_COL = "WSK_DEF") %>%
  filter(LP %in% params$points)

 dataToPlot %>%
   select(-LP) %>%
   arrange(desc(WCSN_DEF)) %>%
   mutate(
     WCSN_ALL = PLN(round(WCSN_ALL)),
     WCSN_DEF = PLN(round(WCSN_DEF)),
     WSK_DEF = percent(WSK_DEF)
          ) %>%
   kable() %>%
   kable_styling()

```



### 2. Wykres
```{r, fig.width=8, echo = FALSE}

ScatterPlotly(dane = dataToPlot,
                  input_proc = params$input_proc,
                  input_wart = params$input_war,
                  Wart_COL = "WCSN_DEF",
                  WSK_COL = "WSK_DEF",
                  fragmentOpisu = "deficytow",
                  source = NA)

```


## 3. YM Plot
```{r, fig.width=8, echo = FALSE}


  ym_select_plotly(dataToPlot = dataToPlot,
                     source = "def_scatter",
                     points = params$points,
                     Wart_COL = "WCSN_DEF",
                     name1 = "Sprzedaz pozostala",
                     name2 = "Sprzedaz deficytow"
                    )


```


###### 99. Parametry wybrane do wygenerowania raportu:
```{r, echo = FALSE}
Opis1 <- paste0(" Raport dotyczy sprzedaży ", Opis)
Opis_daty <- paste0("Zakres dat to od: ", params$d1, " do ", params$d2)

cat(Opis1, "\n", Opis_daty)
```

